### ISSUE TITLE
🐞[Bug]: No Confirmation Message After Clicking "Send Message" in Contact Us Form

### ISSUE THREAD

**Issue by Anwishta** [Anjaliavv51/Retro#339] opened 2024-10-08 12:48 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

In the "Contact Us" footer, after clicking the "Send Message" button, no confirmation popup or alert is displayed. This creates confusion for the user, as they do not receive feedback on whether the message was successfully sent or if there was an error.

### Expected behavior

After clicking "Send Message," a confirmation popup should appear to notify the user if the message was successfully sent or if there was an issue. If any fields are left empty, an error message should be displayed instructing the user to fill out the required fields.

### Add ScreenShots

![Screenshot 2024-10-08 180445](https://github.com/user-attachments/assets/faac2840-158f-4701-a0e1-0f2dad5394de)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24EXTD contributor
- [X] I have starred the repository

**Comment by PulkitShubham** [comment] 2024-10-08 13:10
Hi @Anjaliavv51 ....I think the issue is still unresolved as i tried the same but still no confirmation alert is displayed.Kindly assign me this work I would love to rectify it and further enhance it

**Comment by Codersweta7** [comment] 2024-10-10 07:03
@Anjaliavv51 
Please assign this issue to me ...
First of all I will align the items in a column 
I will also make the page available for all screens 
I will clear up all the mess .
Will create a beautiful responsive page

**Comment by Anjaliavv51** [comment] 2024-10-13 08:22
> @Anjaliavv51 Please assign this issue to me ... First of all I will align the items in a column I will also make the page available for all screens I will clear up all the mess . Will create a beautiful responsive page

go ahead.

**Comment by PulkitShubham** [comment] 2024-10-13 10:00
> Hi @Anjaliavv51 ....I think the issue is still unresolved as i tried the same but still no confirmation alert is displayed.Kindly assign me this work I would love to rectify it and further enhance it

Maam please check my pull request I have already rectified it

**Comment by Anjaliavv51** [comment] 2024-10-13 10:09
> > Hi @Anjaliavv51 ....I think the issue is still unresolved as i tried the same but still no confirmation alert is displayed.Kindly assign me this work I would love to rectify it and further enhance it
> 
> Maam please check my pull request I have already rectified it

Mention the PR number

**Comment by PulkitShubham** [comment] 2024-10-13 10:24
![image](https://github.com/user-attachments/assets/a29d00be-32a8-4442-9c5c-1de663b0918e)
Ma'am this one #347

**Comment by PulkitShubham** [comment] 2024-10-13 10:25
> > > Hi @Anjaliavv51 ....I think the issue is still unresolved as i tried the same but still no confirmation alert is displayed.Kindly assign me this work I would love to rectify it and further enhance it
> > 
> > 
> > Maam please check my pull request I have already rectified it
> 
> Mention the PR number



> > > Hi @Anjaliavv51 ....I think the issue is still unresolved as i tried the same but still no confirmation alert is displayed.Kindly assign me this work I would love to rectify it and further enhance it
> > 
> > 
> > Maam please check my pull request I have already rectified it
> 
> Mention the PR number

![image](https://github.com/user-attachments/assets/6e7ab13b-4c53-4d31-a856-f600cb594d03)
Ma'am this one #347 
Its working absolutely fine.....Please check it

**Closed as completed** 2024-10-15 18:53 UTC
Labels: bug, gssoc-ext, hacktoberfest-accepted
